# serverless.yml

service: kckr-slack-integration

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-central-1

functions:
  app:
    handler: src/app.handler
    environment: 
      NODE_ENV: development
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'